theme: minima
title: PawKanarek
description: > 
  Blog by Paweł Kanarek aka PawKanarek.
  Low-value scribblings that somehow saw the light of day of the public internet.
  PawKanarek is a mythical creature created from the combination of a peacock and a canary, no one has seen it, but here I am.

header_pages:
  - resume.md

minima:
  skin: auto

social_links:
 - { platform: github,         user_url: "https://github.com/PawKanarek" }
 - { platform: linkedin,       user_url: "https://www.linkedin.com/in/pawel-kanarek/" }
 - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/6134430/pawe%c5%82-kanarek" }
 - { platform: x,              user_url: "https://twitter.com/PawKanarek" }