title: PawKanarek
author: 
  name: Paweł Kanarek ML enthusiast
  email: "paw.kanarek@gmail.com"

description: > 
  Low-value scribblings that somehow saw the rays of the public internet.
  A blog written by Machine Learning enthusiast Paweł Kanarek.

header_pages: 
  # - resume-page.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima

minima: 
  skin: auto
  social_links: 
    - platform: github
      user_url: "https://github.com/PawKanarek"
      title: My github reposistory
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/pawel-kanarek/"
      title: My linkedIn profile
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/6134430/pawe%c5%82-kanarek" 
      title: My stackoverflow profile
    - platform: x
      user_url: "https://twitter.com/PawKanarek"
      title: My X profile